CREATE TABLE `address_book`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(15) NOT NULL,
	`email` VARCHAR(50) DEFAULT NULL,
	`comdept` VARCHAR(20) NOT NULL,
	`birth` VARCHAR(10) NOT NULL,
	`tel` VARCHAR(20) DEFAULT NULL,
	`memo` VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY(`id`)
)ENGINE = INNODB DEFAULT CHARSET=UTF8;
